language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
before_install:
- sudo apt-get -qq update
- sudo apt-get install python-numpy
install: pip install .
script: python -c "import cwave"
deploy:
  provider: pypi
  user: davidealbanese
  password:
    secure: QTY8dqEatEqqEkRIUcMp4xBP6bVv3wpn0/wClpVWY1eMSrrB6shcCLaPhdo6bB7BRmccGLJKG3TzAsoHqxEvlO/0yfuDbirCiNUutdOYkSJNEmiCYwpve2lER7otMStlnN04syJqNpC2seHB7UrT01tplH8woh60d7bosuZZ1aU=
  on:
    tags: true
    repo: compbio-fmach/cwave
  distributions: "sdist bdist_wheel"
